quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.ai.gemini.chat-model.enabled=true
quarkus.langchain4j.ai.gemini.embedding-model.enabled=true
quarkus.langchain4j.ai.gemini.embedding-model.model-id=gemini-embedding-001
quarkus.langchain4j.ai.gemini.chat-model.log-requests=true
quarkus.langchain4j.ai.gemini.chat-model.log-responses=true
quarkus.langchain4j.ai.gemini.chat-model.max-tokens=150
# Define o provedor de embeddings como Gemini
#quarkus.langchain4j.embedding-model.provider=ai.gemini
# Define qual modelo do Gemini fará a vetorização
#quarkus.langchain4j.gemini.embedding-model.model-id=text-embedding-004
#--8<-- [start:pgvector]
quarkus.langchain4j.pgvector.dimension=384

#--8<-- [end:pgvector]
#--8<-- [start:rag]
rag.location=src/main/resources/rag
#--8<-- [end:rag]
quarkus.langchain4j.embedding-model.provider=dev.langchain4j.model.embedding.onnx.bgesmallenq.BgeSmallEnQuantizedEmbeddingModel